language: c
dist: bionic
services: docker

stages:
  - stable
  - test
  - machine
  - Test Suite
  - name: package

matrix:
  include:
  # Flatpak package testing ####################################################
  - stage: package
    script:
    - wget https://github.com/claudioandre-br/packages/releases/download/jumbo-dev/flatpak_1_JtR.zip
    - unzip flatpak_1_JtR.zip
    - sudo apt-get install -y flatpak
    - sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - sudo flatpak install -y flathub org.freedesktop.Platform//18.08

    # Install flatpak package
    - sudo flatpak install --user -y --bundle john.flatpak

    # Do some testing
    - sudo flatpak run com.openwall.John
    - sudo flatpak run com.openwall.John --list=build-info
    - export TEST=';full;extra;' # Controls how the test will happen
    - export arch=$(uname -m)
    - export JTR_BIN='sudo flatpak run com.openwall.John'
    - export JTR_CL='flatpak run com.openwall.John'

    # Adjust the testing environment, import and run some testing
    - wget https://raw.githubusercontent.com/claudioandre-br/JtR-CI/master/tests/run_tests.sh
    - source run_tests.sh
  allow_failures:
  - env: TEST="experimental;"

  fast_finish: true

script:
  - .travis/travis-ci.sh

  #DON'T run a test on JtR using a gcc build and OpenCL
   # with ASAN (gcc + OpenCL + ASAN) it works
   # regular (gcc + OpenCL build fails) build fails => (could not find module by name='fglrx')

  #Test JtR using a clang build and OpenCL
   # (clang + ASAN + OpenCL build fails)

  #Test a non SIMD build. OMP and non OpenMP.
   # Note: non OpenMP + clang build fails
